[[Xorg_libXrandr]]
arch = "aarch64"
git-tree-sha1 = "feaf4663528390f6fcea10ab93025856c41ea50f"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "8b7f5860c1260c7f381efe279c9a69b027a93f5e9a8707f17a1c3b5a1003cce8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.aarch64-linux-gnu.tar.gz"
[[Xorg_libXrandr]]
arch = "aarch64"
git-tree-sha1 = "d36b4a144a48aa732dd3c1b20e319768c61feb1a"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "3785eea1c0cdb48be538408ec2b785ba6bd7529947b8a67da9439dfc3c5262c4"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.aarch64-linux-musl.tar.gz"
[[Xorg_libXrandr]]
arch = "aarch64"
git-tree-sha1 = "4c10bf96cebca150bab707701d005c0cc146a6d0"
os = "freebsd"

    [[Xorg_libXrandr.download]]
    sha256 = "f934483a56418dc8316430cb29d66dad27585ec210d1e62e2a5eb13d9287d451"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXrandr]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bbabe5f06bce29309e322fc81b81b211946783ec"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "6dd3848b8f49f24c96b84a55af52977bd11b78eb6b170e1c3ca7f249f79d74e9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXrandr]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f65a9d277099a5325a814a78c74497cecd5c0732"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "a095ea5902caa65a5cdea973586f6c9f2391a7ee768d9734f2f075d8c19b373e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXrandr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d175783885a4c76f96ee09f7e3c12f349300657c"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "50ac3ca5bc032ecf49ee36ed7dd2439f7373c9da4c3bdd3f05954cf11dae7a2b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXrandr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "36db87db6c0cd0458b66470c861d17aab9293905"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "7e3d8ddc17edfa8fbd74a1edba77418c2f349945853180ba1200d1d17d3d243e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXrandr]]
arch = "i686"
git-tree-sha1 = "6099bbdadcaabf425cd9d770a69f6316dec77795"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "26792accc62fb672d3808504215fb45c77d5d10dff61e6c041df5fedddc66253"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.i686-linux-gnu.tar.gz"
[[Xorg_libXrandr]]
arch = "i686"
git-tree-sha1 = "f96d96910b6a155ced54eceb16064f2c67e80560"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "05acaf0f072c56b53cd42a88e4f1b4695849905d97c19aefbd7c7dd171048341"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.i686-linux-musl.tar.gz"
[[Xorg_libXrandr]]
arch = "powerpc64le"
git-tree-sha1 = "975118b06e45eb992e5d8c8e044d495cb73f3926"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "e45c526b36525f75d1527ebb92a64abb01fb2ef8959e4c117a134529225ab17d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXrandr]]
arch = "riscv64"
git-tree-sha1 = "c437aaaed7b9f35ad34135bd47933dc4eee9d4c5"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "bf94772763f88b81bf29a111c2790b91ed2e5d530ee10adc6acad7654415067c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.riscv64-linux-gnu.tar.gz"
[[Xorg_libXrandr]]
arch = "x86_64"
git-tree-sha1 = "f493bc948a41fd60ba4a5864a7127c7a2c8f863b"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "2b2e3a163c5c7f9381749643bca1fd1e8da33cb49008e35d105835302935ae99"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.x86_64-linux-gnu.tar.gz"
[[Xorg_libXrandr]]
arch = "x86_64"
git-tree-sha1 = "69f1f43100eb23b2f2a359946977d99af4868f75"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "42b3df1b9ceea26e2d71bb6dc84094ef1e7f07457ba9d955c86d11213b42115d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.x86_64-linux-musl.tar.gz"
[[Xorg_libXrandr]]
arch = "x86_64"
git-tree-sha1 = "4f3da2ab749109c0c9e29b4bdb0c8bb39d1695e8"
os = "freebsd"

    [[Xorg_libXrandr.download]]
    sha256 = "f73ba864190d677001e5fd43eb474de4b51fc24ac14340d70ca241524ec0087e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.5+0/Xorg_libXrandr.v1.5.5.x86_64-unknown-freebsd.tar.gz"
