[[Xorg_libXrandr]]
arch = "aarch64"
git-tree-sha1 = "bcfa267ccd3d527d1ed5306f1e3198a5845f7a11"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "2f06377a04ac4deb477cf01cc63fe86bbef6d579e0c4f9609a62323370a13679"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.2+1/Xorg_libXrandr.v1.5.2.aarch64-linux-musl.tar.gz"
[[Xorg_libXrandr]]
arch = "aarch64"
git-tree-sha1 = "19139572d5d7eff61d7a0c6fb086b182d059742f"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "2b7a427e4c76eb745870027bca251266d6aab9f32564a09f84bcd0d24c39679a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.2+1/Xorg_libXrandr.v1.5.2.aarch64-linux-gnu.tar.gz"
[[Xorg_libXrandr]]
arch = "x86_64"
git-tree-sha1 = "8e7d7459fcaa7e17eb79b52d4c784f8923cd93c1"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "af4bac7e7ef919e4594dbbffe21b5d56dd6ba581f45edc7409c6dcaa277d227c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.2+1/Xorg_libXrandr.v1.5.2.x86_64-linux-gnu.tar.gz"
[[Xorg_libXrandr]]
arch = "powerpc64le"
git-tree-sha1 = "7ce4040d04b162e240d216561ed870c03ca1f340"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "976e2787a8870de79947ec265ac82826b8366d9401789d69a0ab2a3403052a67"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.2+1/Xorg_libXrandr.v1.5.2.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXrandr]]
arch = "x86_64"
git-tree-sha1 = "fcb4a7765f5cd3d952082150ed0d0981fc05d39f"
os = "freebsd"

    [[Xorg_libXrandr.download]]
    sha256 = "839398a16e2857afbc86fbb96d7658d1d992418ce8454dc3cd8a678321169247"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.2+1/Xorg_libXrandr.v1.5.2.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libXrandr]]
arch = "i686"
git-tree-sha1 = "e9109aac965745b376308d5feca5b3a96cfa6b56"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "24207c691b01b332fdf6a6086abbfa8f2090e456b3f7335f1e0e80b0e37fbab2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.2+1/Xorg_libXrandr.v1.5.2.i686-linux-gnu.tar.gz"
[[Xorg_libXrandr]]
arch = "i686"
git-tree-sha1 = "726773c93a9c7aa19e57d5bb5345d7f39103a5f2"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "27d85aa93e3b0694284f41ecd772ee0baa6f747916ed8d66f3650373e5680177"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.2+1/Xorg_libXrandr.v1.5.2.i686-linux-musl.tar.gz"
[[Xorg_libXrandr]]
arch = "armv7l"
git-tree-sha1 = "b8b855639f54ffd05cec8e7adcf016aec53a77ff"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "41724e0f53469379dab814cc291fc030af97f0a5f99b2a0d32f9e99c1fa3be69"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.2+1/Xorg_libXrandr.v1.5.2.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXrandr]]
arch = "x86_64"
git-tree-sha1 = "5862205b46db1d5841149846f87316e223817d36"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "b4dfe958a3be5f9c884b46205551a79e9733097f3a2b17b6d37bf6a7e173ecc1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.2+1/Xorg_libXrandr.v1.5.2.x86_64-linux-musl.tar.gz"
[[Xorg_libXrandr]]
arch = "armv7l"
git-tree-sha1 = "2666b39fdc2b4fb009c441d6d8e4676fbe0d573e"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "1a32747795a11a2ff1910c0b6cfb5a5bd9d2cab2d62891936866f562e7ac5bf7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.2+1/Xorg_libXrandr.v1.5.2.armv7l-linux-musleabihf.tar.gz"
