[[Xorg_libXrandr]]
arch = "aarch64"
git-tree-sha1 = "87080b80c3b7e872977e7e87eabb4e9fd25c1af9"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "4a1856ca22dc4e21079ab9fc4e34d20861c4fbf3d3cf0d44e1bfc42f17624ef0"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.4+0/Xorg_libXrandr.v1.5.4.aarch64-linux-gnu.tar.gz"
[[Xorg_libXrandr]]
arch = "aarch64"
git-tree-sha1 = "f5a2dcbf04b170a61dbc4d4880a1f527e15b2c92"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "bc054eb0717221af7a09f0ba0b5a698ba8f1fb3cb424d394ece051fc73c998f3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.4+0/Xorg_libXrandr.v1.5.4.aarch64-linux-musl.tar.gz"
[[Xorg_libXrandr]]
arch = "aarch64"
git-tree-sha1 = "065f5afa009d3f2c68e7326b0b7a2a8e67be93f2"
os = "freebsd"

    [[Xorg_libXrandr.download]]
    sha256 = "e8c2d1aec3937680291e07f882c0e1a3ac4c9332fe69671777964a685eb5870b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.4+0/Xorg_libXrandr.v1.5.4.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXrandr]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9c78f51ff01c046488622c974f8c21d62be16d9f"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "416cde04d5dfbbbed8f9850d78fa24fe08033c046a881cacfa137b19a026ee5f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.4+0/Xorg_libXrandr.v1.5.4.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXrandr]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "45fa56a4f246d5d846678e033546c830ccc2d33d"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "69710b83830785ee38090f03f280029a1566b34ab9bbeea0b863bb94100143d1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.4+0/Xorg_libXrandr.v1.5.4.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXrandr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "739d4ce0bc22b8a991df6860cb02a6afeddf23c4"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "1722dbdb24aef476fbd20ac3d7d09cff871976df16de44094ea25b1e9b9970f6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.4+0/Xorg_libXrandr.v1.5.4.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXrandr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fd8b8c412e12284cb6af65891cb4d3892ae428bf"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "279e07b7923315c180a6ec43d4a41e3da040bdbea58146aad506c64babeba1b8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.4+0/Xorg_libXrandr.v1.5.4.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXrandr]]
arch = "i686"
git-tree-sha1 = "8acc3b85a222feec4783b6e01e16b40108ef8ef9"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "aa363f5a344a5ecb21960cbd274f747e5495422f48aab49fb9fdd416e4a123fa"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.4+0/Xorg_libXrandr.v1.5.4.i686-linux-gnu.tar.gz"
[[Xorg_libXrandr]]
arch = "i686"
git-tree-sha1 = "5eeeff666bcfc25cc61bf7284973fb8e345b55e9"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "7d2940cbf0b657b494dd0ebaacf0371cbe1ff82c9d00904a5be99fdd255de03c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.4+0/Xorg_libXrandr.v1.5.4.i686-linux-musl.tar.gz"
[[Xorg_libXrandr]]
arch = "powerpc64le"
git-tree-sha1 = "61d7beb75132d333a259d1e8b9d3f7ea087427f3"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "619e187e962d09dd5371d9fb066570c4a549a49db394041397f430a97184ad5d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.4+0/Xorg_libXrandr.v1.5.4.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXrandr]]
arch = "x86_64"
git-tree-sha1 = "f2af068a5dffc0225d3e1e01e896cd11792ecfe0"
libc = "glibc"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "4e4310ab459a501b67ee1bc2e20ef4ba7c7f4300cdcb920d30750e7abfa236cb"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.4+0/Xorg_libXrandr.v1.5.4.x86_64-linux-gnu.tar.gz"
[[Xorg_libXrandr]]
arch = "x86_64"
git-tree-sha1 = "4490862119df740f79618acc6b3794c6371a51d1"
libc = "musl"
os = "linux"

    [[Xorg_libXrandr.download]]
    sha256 = "2a40e11b588fa02026889c9bb8cb0052a80cd0183e1beb42f60670ab283e339d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.4+0/Xorg_libXrandr.v1.5.4.x86_64-linux-musl.tar.gz"
[[Xorg_libXrandr]]
arch = "x86_64"
git-tree-sha1 = "3e36152ca7278537c10e0f23b342d81b91aceee7"
os = "freebsd"

    [[Xorg_libXrandr.download]]
    sha256 = "1e07d6434e2e76ab023b7ea15d8ce516bf9fc853a39a526673657e38057fd792"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXrandr_jll.jl/releases/download/Xorg_libXrandr-v1.5.4+0/Xorg_libXrandr.v1.5.4.x86_64-unknown-freebsd.tar.gz"
